### ISSUE TITLE
Way to pick colours for each header level

### ISSUE THREAD

**Issue by Psypher1** [rivea0/obsidian-prime#2]
The header colours are nice, you thought about it a lot. However, a way to change what each header level colour is would be awesome.

**Comment by rivea0** [comment]
Thank you. The new release (v1.0.1) includes the option to change each heading color separately in Style Settings. Let me know if you have any issues after updating. Thanks again!

**Comment by Psypher1** [comment]
Without a doubt it helps. Thank you for getting on it so quickly. I did notice something with a couple of the colours, possibly i am seeing things but here are images

Edit: I was seeing things. It looked to me like green and blue where the same colour. They are close to each other on the palette.
![1](https://github.com/rivea0/obsidian-prime/assets/34038162/9569a483-67e9-46a9-a31d-ad2ccc6148b3)

![2](https://github.com/rivea0/obsidian-prime/assets/34038162/ed1dabb9-484c-4c84-99bc-4d90ad8b9bb7)
