### ISSUE TITLE
Could we get colour options for bold and italic

### ISSUE THREAD

**Issue by Psypher1** [rivea0/obsidian-prime#3]
If it's not too much of a bother, would it be possible to get the colour options like we have for headings on bold and italic text?

**Comment by rivea0** [comment]
That's a great idea! I've also been thinking of implementing that option, just released a new version (1.0.2) that lets you customize text decoration colors in Style Settings.

Thanks so much for the feedback, I hope it solves the issue. Feel free to reach out if you have more ideas. Thanks again!
