### ISSUE TITLE
A bit more visual distinction between blue and green

### ISSUE THREAD

**Issue by Psypher1** [rivea0/obsidian-prime#4]
I mentioned this last time, but I saw the difference after a bit. However, a slight tweak would make each a bit more distinct from the other. To confirm my suspicions, I went into the css and sure enouth

![colors](https://github.com/rivea0/obsidian-prime/assets/34038162/c9c4c2d6-dca3-4004-8ee7-40666d351aa7)

In the image, blue and green are almost the same color.

**Comment by rivea0** [comment]
@Psypher1 thanks for opening this issue. It seems to be related to dark mode only. 

I initially have chosen the colors mostly from the tetrad and polyad combinations of the base purple color, you can see here at the bottom: https://hue.tools/info?format=hex&color=9ca0fa

In the new update (v1.0.3) I added an option to use an alternative green color in a new tweaks section in Style Settings — it is based on the same combinations so as not to disrupt the color scheme, I hope makes it more distinctive. 

Here is an example difference in headings with the old and new green:

| Old                 | New                 |
| ------------------- | ------------------- |
| ![old-green](https://github.com/rivea0/obsidian-prime/assets/58330360/cee6ad4d-a86e-45b7-9b04-9f27bdfebe4a) | ![new-green](https://github.com/rivea0/obsidian-prime/assets/58330360/73e96de9-092f-42c8-808e-6e10c9caef3a) |

It stays as an option for now, but I can replace it with the default one in the future.

Thanks again!

**Comment by Psypher1** [comment]
Ah, I see...

Thank you! It does make it more distinctive.
