### ISSUE TITLE
Dropdown to choose accent color from therme colors

### ISSUE THREAD

**Issue by Psypher1** [rivea0/obsidian-prime#6]
I love the purple as the accent color. I wonder if it would be possible to use one of the colors in the theme as an accent. Kind of the same way we can choose heading colors

**Comment by rivea0** [comment]
Hi @Psypher1, thanks for opening this issue!

In the new version (v1.1.2), I added an option that you can find in Style Settings to change the Interactive Accent Color with default color selections. 
There is one issue that needs mentioning, the text selection background color also changes when you change the accent, I'm working to find a solution to preserve the default as well. In the meantime, I hope the update resolves this issue!

**Comment by Psypher1** [comment]
Yes @rivea0! The update is exactly what I had in mind. Thank you.

As for the highlighting issue, I am not experiencing anything to that effect. I will leave you to it though.

Thank you once more.
